### ISSUE TITLE
watchdog test doesn't work on aarch64

### ISSUE THREAD

**Issue by rayx** [autotest/tp-qemu#1637]
It's because the QEMU command line generated in check_watchdog_support() doesn't contain "-M" option. 

While the issues can be easily fixed by modifying the test code to add -M option when test system is aarch64 server, a better method is to reuse DevContainer.execute_qemu(). However, at the time when the test performs the check, the DevContainer object is not created yet. 

That leads to me think avocado (or avocado-vt) should have a test system configuration database, like facts in Ansible. Maybe the params in avocado-vt is used for this purpose? If so, I think the issue should be fixed by getting supported watchdog devices in avocado-vt code and save the values in, say, 'supported_watchdog_types'. Then modify this test to just check if the watchdog type being tested is among that parameter's value.

That's just my thought. I work around the issue by setting the following in test config:

    watchdog_type_check = " -M virt -watchdog '?'"

**Comment by vivianQizhu** [comment]
Worth to think about. Or to solve it we can use `DevContainer.execute_qemu()` without vm, like: `DevContainer(qemu_binary, vmname=None).execute_qemu()`? Some of DevContainer functions should be independent from vm, so that's another issue I think worth to think about. 
The configuration database description is truly similar with params' function, and from my view what the qemu binary supported does not have to be stored, it is stored in qemu binary anyway, that is also a time cost or space cost question. And as a test suit, the params mainly focus on the test configurations looks better for me.

**Comment by luckyh** [comment]
@rayx yes, that's what we planned to do, not only for this watchdog specified issue, but also for all things required pre-configured. The idea is doing something which is already done by libvirt (simply, by porting libvirt codes..).

Well, currently we are focusing on some other tough tasks (refactoring the storage management layer, ..), it has to be deferred to the future.

It will be appreciated if you have time to help accomplish that. And for this issue, I'm agree with your temporary solution if it works.

Thanks.

**Comment by PaulYuuu** [comment]
https://github.com/autotest/tp-qemu/pull/2330 has addressed this issue.
